### ISSUE TITLE
opam file: removal incomplete

### ISSUE THREAD

**Issue by fdopen** [xvw/olmi#1]
olmiExamples gets installed, too, but it's not removed during uninstallation. `opam install olmi && opam reinstall olmi` will fail therefore.

**Comment by xvw** [comment]
Thanks, it's my first "submission" and I still a Noob. 
The new version (1.1) avoid this problem. 
OlmiExamples is not installed, but the code stay at his place (to be readble). 
Thanks for the point. You can 
`ocamlfind remove olmiExamples`.
